import glob
import os
import re
from pathlib import Path
from sys import argv
from typing import Any, Dict, List

from config_parser import parseProjectConfig

PREFIX = "|"
POSTFIX = "|"
PROJECTEER_FOLDER = ".projecteer"
# these special variables are generated by projecteer
# SPECIAL = ["PROJECTEER_GENERATED_FILES"]


def findFilesToBeConfigured() -> List[str]:
    paths = []
    # configured sandwiched
    paths += glob.glob('*.configured.*', recursive=True)  # current dir
    paths += glob.glob('**/*.configured.*', recursive=True)  # any sub dir

    # configured in the beginning
    paths += glob.glob('.configured.*', recursive=True)
    paths += glob.glob('**/.configured.*', recursive=True)

    # configured in the end
    paths += glob.glob('*.configured', recursive=True)
    paths += glob.glob('**/*.configured', recursive=True)
    return sorted(list(set(paths)))


def replace(content: str, config: Dict[str, Any]):
    replaced = content
    for key, value in config.items():
        matcher = f"{PREFIX}{key}{POSTFIX}"
        replaced = replaced.replace(matcher, str(value))

    # \|(.*?)\|
    regex = re.compile(rf"{re.escape(PREFIX)}(.*?){re.escape(POSTFIX)}")
    matches = re.findall(regex, replaced)
    for match in matches:
        if match != "":
            print(f"NO VARIABLE FOUND FOR: {match}")

    return replaced


def cleanup():
    try:
        with open(f"{PROJECTEER_FOLDER}/generatedFiles", 'r') as f:
            print("cleaning up...")
            for file in f:
                filePath = file.removesuffix("\n")
                try:
                    os.remove("./" + filePath)
                    print(f"  removing {filePath}")
                except FileNotFoundError as fnfe:
                    print(f"  failed, because {filePath} does not exist")

        os.remove(f"{PROJECTEER_FOLDER}/generatedFiles")
        if not os.listdir(PROJECTEER_FOLDER):
            os.rmdir(PROJECTEER_FOLDER)
    except FileNotFoundError as fnfe:
        print("No generated Files...")
    exit(0)


def tryLoadAlreadyGeneratedFilePaths():
    os.makedirs(PROJECTEER_FOLDER, exist_ok=True)
    with open(PROJECTEER_FOLDER+"/generatedFiles", 'a') as f:
        pass
    with open(PROJECTEER_FOLDER+"/generatedFiles", "r") as f:
        return f.read().splitlines()


##################################################################
### MAIN #########################################################
##################################################################


if __name__ == "__main__":
    if '--cleanup' in argv:
        cleanup()

    # all filePaths that got generated
    allGeneratedFilePaths = tryLoadAlreadyGeneratedFilePaths()

    print("loading project configuration ...")
    with open('project.config', 'r') as f:
        configContent = f.readlines()

        projectConfig = None
        try:
            projectConfig = parseProjectConfig(configContent)
        except Exception as e:
            print(e)
            exit(-1)
        # print(str(projectConfig))

    print("looking for files to be configured...")
    filePaths = findFilesToBeConfigured()

    print("Creating/updating files...")
    # pregenerate all file paths to setup the GENERATED_FILES variable
    allGeneratedFilePaths = list(set(
        allGeneratedFilePaths +
        # replace os.sep with linux slash, because of gitignore working better with linux slash
        [path.replace(".configured", "").replace(os.sep, "/") for path in filePaths]
    ))
    projectConfig["PROJECTEER_GENERATED_FILES"] = "\n".join(
        allGeneratedFilePaths)
        
    for filePath in filePaths:
        with open(filePath, 'r') as f:
            content = "".join(f.readlines())
            replaced = replace(content, projectConfig)

            fileName = os.path.basename(filePath)
            generatedFilePath = filePath.replace(".configured", "")
            generateadFileName = os.path.basename(generatedFilePath)
            #  replacedFilePath

            doing = "updating" if os.path.exists(
                generatedFilePath) else "creating"
            print(f"  {doing} {generatedFilePath}")
            with open(generatedFilePath, 'w') as w:
                w.write(replaced)
                # if input(f"write to {filename}?") == 'Y':
                #     w.write(replaced)
                # else:
                #     print("done nothing")

    with open(PROJECTEER_FOLDER+"/generatedFiles", 'w') as f:
        f.writelines("\n".join(allGeneratedFilePaths))
